# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Automation Workflow

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLabdaTest=true -DisHeadless=false
      
    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
       name: Test logs
       path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
       name: screenshots
       path: screenshots/

    - name: Upload HTML Report as Artifact
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
       name: HTML Report
       path: extentReportFile.html
       
    - name: Test Execution Status
      if: always()
      run: echo"************Test Execution Completed*************"

    - name: Copy Report to gh-pagesFolder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R extentReportFile.html public/extent-reports/
        ls -l
        
    - name: Deploy
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4.7.6
      with:
       folder: public/extent-reports
       tokens: ${{secrets.AUTO1234}}
       clea: true
        

  
